// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SetTracking(arg1) {
  return window['go']['main']['DaemonService']['SetTracking'](arg1);
}

export function Status() {
  return window['go']['main']['DaemonService']['Status']();
}
