// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {main} from '../models';

export function Attach(arg1:context.Context):Promise<void>;

export function Cancel():Promise<main.State>;

export function GetState():Promise<main.State>;

export function Pause():Promise<main.State>;

export function Resume():Promise<main.State>;

export function Shutdown():Promise<void>;

export function SkipBreak():Promise<main.State>;

export function Start(arg1:string,arg2:number):Promise<main.State>;

export function StartBreak(arg1:number):Promise<main.State>;
