// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Attach(arg1) {
  return window['go']['main']['TimerService']['Attach'](arg1);
}

export function Cancel() {
  return window['go']['main']['TimerService']['Cancel']();
}

export function GetState() {
  return window['go']['main']['TimerService']['GetState']();
}

export function Pause() {
  return window['go']['main']['TimerService']['Pause']();
}

export function Resume() {
  return window['go']['main']['TimerService']['Resume']();
}

export function Shutdown() {
  return window['go']['main']['TimerService']['Shutdown']();
}

export function SkipBreak() {
  return window['go']['main']['TimerService']['SkipBreak']();
}

export function Start(arg1, arg2) {
  return window['go']['main']['TimerService']['Start'](arg1, arg2);
}

export function StartBreak(arg1) {
  return window['go']['main']['TimerService']['StartBreak'](arg1);
}
